spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format-sql: true
                dialect: org.hibernate.dialect.PostgreSQL81Dialect
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/notes
        username: postgres
        password: "@host_admin"
server:
    error:
        include-stacktrace: never